spring:
  profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/ticket
    username: root
    password: Welcome1 #Admin@123!
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MariaDB10Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update  #update,none,create, create-drop, validate
    open-in-view: false